apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    component: elasticsearch
    role: client
spec:
  type: LoadBalancer
  selector:
    component: elasticsearch
    role: client
  clusterIP: 10.0.0.110
  ports:
  - name: http
    nodePort: 30101
    port: 9200
    protocol: TCP
