apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    component: kibana
    role: web
spec:
  type: LoadBalancer
  selector:
    app: kibana
    tier: frontend
  ports:
  - name: kibana-expose-service
    port: 80
    protocol: TCP
    nodePort: 30102
    targetPort: 5601
